---
layout: post
title: python列表的操作方法
date: 2018-9-3
categories: blog
tags: [python]
description: 文艺的流氓。
---
#### 初识递归
```
在函数中调用递归
一个函数直接或者间接调用自己，那么这个函数就称为递归函数。
那这个函数如果一直自己调用自己，是不是会一直处于死循环状态，答案是不会，因为python为了杜绝此类现象，强制的将递归层数控制在了997层。
```
```python
def demo():               # 在函数内部一直在调用demo函数。
    print('我最帅')       # 在内存中一直会生成新的一个空间
    demo()                # 所以才会报错，函数本身并没有错误
demo()
RecursionError: maximum recursion depth exceeded while calling a Python object
报错是一个内存保护机制。
```
##### 可以使用测试知道一下，递归的最大深度是多少。我这里是998/997
```python
a = 0
def demo():
    global a
    a +=1
    print(a)
    demo()
demo()
```
```
同样这个值是能够修改的。使用sys模块
我自己的电脑只能够跑到8700多。
这个东西是需要看自己电脑的配置的
```
```python
import sys
sys.setrecursionlimit(100000)
a = 0
def demo():
    global a
    a = a+1
    print(a)
    demo()
demo()
```
#### 递归的缺点是占内存
#### 递归的优点是代码简单
```python
def demo(a):
    if  a == 4:
        return 40
    elif a > 0 and a < 4:
        return demo(a+1) + 2
print(demo(1))
```
#### 输出的结果是46.那么是怎么来的呢
#### 第一次调用demo函数传入的是1，那么也是可以这样写
```python
def demo(1):
    if  1 == 4:
        return 40
    elif 1 > 0 and 1 < 4:
        return demo(44) + 2    # 下面是把44返回到了这里。这里的结果也就是46
程序运行到上面这一次的时候。又调用了demo函数
```
#### 发生了第二次调用
```python
def demo(2):
    if  2 == 4:
        return 40
    elif 2 > 0 and 2 < 4:
        return demo(42) + 2  # 下面是把42返回到了这里。这里的结果也就是44
程序运行到上面这一次的时候。又调用了demo函数
```
#### 发生了第三次调用
```python
def demo(3):
    if  3 == 4:
        return 40
    elif 3 > 0 and 3 < 4:
        return demo(40) + 2  # 返回到了这里的demo函数内 这里的结果就是42.
程序运行到上面这一次的时候。又调用了demo函数
```
#### 到了第四次条件就满足了。3+1=4嘛
```python
def demo(4):
    if  4 == 4:
        return 40       # 这时候是把四十返回给了他的调用者
    elif a > 0 and a < 4:
        return demo(a+1) + 2   # 也就是这里的a
所以最后的结果会是46
```
#### 总结：认识了一下递归，递归是分两个步骤的先是递后是归。可能我自己写的不好。上面这个递归程序我自己的理解就是。把一直在函数内部调用。最后条件满足了返回的结果全部都是同一个函数。